#!/usr/bin/env bash
# Run from the candidate checkout on a dedicated staging VM, never the live VM.
set -Eeuo pipefail
umask 077
archive=${1:?Usage: bash scripts/staging/import-clone.sh /absolute/snapshot.tar.gz SHA256}
expected=${2:?Supply the verified SHA256 printed for the archive}
[[ "$archive" = /* && "$expected" =~ ^[0-9a-f]{64}$ ]] || exit 1
test "$(sha256sum "$archive" | cut -d ' ' -f 1)" = "$expected"
if docker inspect metrotech-erf-app >/dev/null 2>&1 || docker inspect metrotech-erf-app-1 >/dev/null 2>&1; then
  echo 'Use a dedicated staging VM. Existing production/development app detected.' >&2; exit 1
fi
repo=$(git rev-parse --show-toplevel)
candidate=$(git -C "$repo" rev-parse HEAD)
git -C "$repo" diff --quiet
git -C "$repo" diff --cached --quiet
run=$(mktemp -d "$HOME/ems-staging.XXXXXX")
project="ems-staging-$(date -u +%Y%m%d%H%M%S)"
# Trust only the private export generated by export-production.sh.
tar --no-same-owner -xzf "$archive" -C "$run"
printf '%s\n' "$candidate" > "$run/candidate-sha"
printf '%s\n' "$project" > "$run/project"
mkdir "$run/code"
git -C "$repo" archive "$candidate" | tar -x -C "$run/code"
cp "$repo/scripts/staging/compose.yml" "$run/compose.yml"
cp "$repo/scripts/staging/Caddyfile" "$run/Caddyfile"
printf 'POSTGRES_DB=ems_staging\nPOSTGRES_USER=ems_staging\nPOSTGRES_PASSWORD=%s\nEMS_STAGE_SESSION_SECRET=%s\nEMS_STAGE_URL=http://127.0.0.1:18090\n' \
  "$(openssl rand -hex 24)" "$(openssl rand -hex 48)" > "$run/runtime.env"
compose=(docker compose --project-directory "$run" -p "$project" -f "$run/compose.yml")
"${compose[@]}" build app
for folder in pdfs signatures; do
  "${compose[@]}" run --rm --no-deps --entrypoint node -v "$run:/snapshot:ro" app \
    /snapshot/hash-documents.cjs "/snapshot/$folder" > "$run/$folder-restored.json"
  cmp "$run/$folder-before.json" "$run/$folder-restored.json"
done
"${compose[@]}" up -d --wait db mailpit
"${compose[@]}" exec -T db pg_restore --exit-on-error --no-owner --no-acl -U ems_staging -d ems_staging < "$run/production.dump"
"${compose[@]}" run --rm --no-deps app node scripts/staging/verify-clone.js --snapshot > "$run/db-before.json"
# Already-EMS clone: apply ONLY the additive multi-role migration, never the old ERF cutover.
"${compose[@]}" exec -T db psql -v ON_ERROR_STOP=1 -U ems_staging -d ems_staging < "$run/code/sql/migrations/018-assigned-multi-role.sql"
"${compose[@]}" run --rm --no-deps -v "$run/db-before.json:/snapshot/db-before.json:ro" app node scripts/staging/verify-clone.js --compare /snapshot/db-before.json
"${compose[@]}" run --rm --no-deps app node scripts/staging/verify-clone.js
"${compose[@]}" up -d app preview
ready=false
for attempt in $(seq 1 45); do
  if curl --connect-timeout 2 --max-time 3 -fsS http://127.0.0.1:18090/health > "$run/health.json"; then ready=true; break; fi
  sleep 1
done
test "$ready" = true
printf '\nSTAGING_READY\nDirectory: %s\nProject: %s\nCandidate: %s\nApp: http://127.0.0.1:18090\nCaptured email: http://127.0.0.1:18091\n' "$run" "$project" "$candidate"
echo 'Use an SSH tunnel for access. Workflow email is captured locally, never relayed to real recipients.'
